name: CI Test Workflow

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET 6
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '6.0.x'  # Projenizin .NET sürümüne göre ayarlayın

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      id: run-tests  # Bu adı kullanarak daha sonra test sonuçlarına erişebiliriz
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Check test result
      if: steps.run-tests.outcome != 'success'  # Eğer testler başarısız olduysa
      run: |
        echo "Tests failed. Stopping the merge."
        exit 1  # Hata kodu ile çıkış yaparak birleştirmeyi durdur
