name: CI - Logic Error Detection

on:
  pull_request:
    branches: [ "master" ]  # Pull request'ler için master dalını izle

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Execute unit tests
      run: dotnet test --no-build --verbosity normal  # Testleri çalıştır
